### ISSUE TITLE
Error in aggregate.formula(...)

### ISSUE THREAD

**Issue by kmavrommatis** [mskilab-org/JaBbA#85]
Running:

```
jba manta/manta.tumor.svs.hg38.vcf cov.rds --field ratio --purity 0.7 --outdir $PWD/jabba --name test --cores 8 --gurobi TRUE
```

The cov.rds file contains the column `ratio` which is the ratio of the fragCounter values for tumor/normal.

After about 2h it 
produces the error:

```
.
.
.
JaBbA 2023-02-16 22:28:39: Number of gaps with nonzero width: 12516
JaBbA 2023-02-16 22:28:39: Number of segments before gap filtering: 14982
JaBbA 2023-02-16 22:28:40: 5987 segments produced after gap filtering
JaBbA 2023-02-16 22:28:40: creating karyograph
JaBbA 2023-02-16 22:30:03: WARNING: big karyograph > 50000 nodes, may take longer to finish.
JaBbA 2023-02-16 22:30:41: Definining coverage good quality nodes as >=50% bases covered by non-NA and non-Inf values in +/-100KB region
JaBbA 2023-02-16 22:30:41: Hard setting 58.258246 Mb of the genome to NA that didn't pass our quality threshold
JaBbA 2023-02-16 22:30:41: Using loess to fit mean to variance relationship in segments with greater than 1 bins
JaBbA 2023-02-16 23:10:31: Using ppgrid to estimate purity ploidy
JaBbA 2023-02-16 23:10:31: setting up ppgrid matrices ..

.
.
JaBbA 2023-02-16 23:11:36: Built gGraph with 1181150 nodes, 1759858 edges, purity 0.7, and ploidy 1.25
Error in aggregate.formula(...) :
  argument 'x' is  missing -- it has been renamed from 'formula'
Calls: suppressPackageStartupMessages ... vaggregate -> aggregate -> aggregate -> aggregate.formula
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
```

I have tried with different purities an different variations of the cov.rds file but the error is the same

```
R version 4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"

GUROBI v10.0.0
```

Thanks in advance for your help

**Comment by imielinski** [comment]
Hi – sorry about this, can you try with this is a known issue with the syntax of the base aggregate function changing in R 4.2 in a bit of a non-backward compatible way. 

Can you try with R 4.1 or earlier? We have to update our code to be compatible with R 4.2 but unfortunately this issue affects several parts of our code base.  

Marcin

 

Running:
jba manta/manta.tumor.svs.hg38.vcf cov.rds --field ratio --purity 0.7 --outdir $PWD/jabba --name test --cores 8 --gurobi TRUE
The cov.rds file contains the column ratio which is the ratio of the fragCounter values for tumor/normal.

After about 2h it
produces the error:
.
..
.
JaBbA 2023-02-16 22:28:39: Number of gaps with nonzero width: 12516
JaBbA 2023-02-16 22:28:39: Number of segments before gap filtering: 14982
JaBbA 2023-02-16 22:28:40: 5987 segments produced after gap filtering
JaBbA 2023-02-16 22:28:40: creating karyograph
JaBbA 2023-02-16 22:30:03: WARNING: big karyograph > 50000 nodes, may take longer to finish.
JaBbA 2023-02-16 22:30:41: Definining coverage good quality nodes as >=50% bases covered by non-NA and non-Inf values in +/-100KB region
JaBbA 2023-02-16 22:30:41: Hard setting 58.258246 Mb of the genome to NA that didn't pass our quality threshold
JaBbA 2023-02-16 22:30:41: Using loess to fit mean to variance relationship in segments with greater than 1 bins
JaBbA 2023-02-16 23:10:31: Using ppgrid to estimate purity ploidy
JaBbA 2023-02-16 23:10:31: setting up ppgrid matrices ..
 
..
.
JaBbA 2023-02-16 23:11:36: Built gGraph with 1181150 nodes, 1759858 edges, purity 0.7, and ploidy 1.25
Error in aggregate.formula(...) :
  argument 'x' is  missing -- it has been renamed from 'formula'
Calls: suppressPackageStartupMessages ... vaggregate -> aggregate -> aggregate -> aggregate.formula
In addition: There were 50 or more warnings (use warnings() to see the first 50)
Execution halted
I have tried with different purities an different variations of the cov.rds file but the error is the same
R version 4.2.2 Patched (2022-11-10 r83330) -- "Innocent and Trusting"
Thanks in advance for your help

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>


-- 

This message is for the recipient’s use only, and may contain 
confidential, privileged or protected information. Any unauthorized use or 
dissemination of this communication is prohibited. If you received this 
message in error, please immediately notify the sender and destroy all 
copies of this message. The recipient should check this email and any 
attachments for the presence of viruses, as we accept no liability for any 
damage caused by any virus transmitted by this email.

**Comment by kmavrommatis** [comment]
Thank you
Switched to  R 4.1 but now I get the error:

```
        HLA-DRB1*15:03:01:01:11567
        HLA-DRB1*15:03:01:02:11569
        HLA-DRB1*16:02:01:11005
JaBbA 2023-02-17 23:01:58: Number of gaps with nonzero width: 6732
JaBbA 2023-02-17 23:01:58: Number of segments before gap filtering: 12719
JaBbA 2023-02-17 23:01:58: 5987 segments produced after gap filtering
JaBbA 2023-02-17 23:02:14: Brand new function for reciprocal junctions calling.
..................................................................................Error in replCmat4(x, i1 = if (iMi) 0:(di[1] - 1L) else .ind.prep2(i,  :
  number of items to replace is not a multiple of replacement length
Calls: suppressPackageStartupMessages ... callGeneric -> eval -> eval -> [<- -> [<- -> replCmat4
In addition: There were 12 warnings (use warnings() to see them)
Execution halted

```
