### ISSUE TITLE
CPLEX or Gurobi optimizers

### ISSUE THREAD

**Issue by tanasa** [mskilab-org/JaBbA#88]
Congratulations to the authors for developing a great algorithm !

Would it be possible to use JaBbA or the docker version without CPLEX or Gurobi optimizers ?
Unfortunately, I do not have the license, and the message that I am getting is :

__JaBbA 2023-03-07 15:04:29: Starting analysis in /Users/tanasab
Error in jerror("${CPLEX_DIR}/cplex not found") : 
  JaBbA 2023-03-07 15:04:29: ${CPLEX_DIR}/cplex not found
Calls: suppressPackageStartupMessages -> withCallingHandlers -> JaBbA -> jerror
In addition: Warning messages:
1: multiple methods tables found for ‘seqinfo<-’_

Thanks so much, 

Bogdan

**Comment by mskilab** [comment]
many thanks Bogdan!
Unfortunately we currently only support CPLEX or Gurobi.
I know that there are some free MIP solvers out there - for example google
has OR tools - but we haven't yet played with them.  Though my
understanding is that they are much much slower and may not be able to
handle problems of the size that we encounter with JaBbA.
Marcin

**Comment by tanasa** [comment]
Thanks a lot Marcin for the prompt reply !

Shall we use only as a test example only one chromosome, is there a way to deactivate the necessity of CPLEX or Gurobi ?
I would love to use JaBaA on some WGS in-house data that we have and we can use higher computational power on aws.

Or, is there any other way to get JaBaA to work in the absence of CPLEX or Gurobi ? It would be great if you could please confirm.

Much thanks, 

Bogdan  

ps : do you mind if we take part of conversation off-line, it is about CNA / LOH. Thanks.

Would it be possible to set JVbaA

**Comment by imielinski** [comment]
Hi Bogdan- No, unfortunately it does not work without CPLEX or gurobi- this is the core of the algorithm !  But if you are at an academic institution you should have free access to both CPLEX and gurobi.Sure, you can reach me at ***@***.*** On Mar 8, 2023, at 5:17 PM, Bogdan Tanasa ***@***.***> wrote:﻿
Thanks a lot Marcin for the prompt reply !
Shall we use only as a test example only one chromosome, is there a way to deactivate the necessity of CPLEX or Gurobi ?
I would love to use JaBaA on some WGS in-house data that we have and we can use higher computational power on aws.
Or, is there any other way to get JaBaA to work in the absence of CPLEX or Gurobi ? It would be great if you could please confirm.
Much thanks,
Bogdan
ps : do you mind if we take part of conversation off-line, it is about CNA / LOH. Thanks.
Would it be possible to set JVbaA

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

This message is for the recipient’s use only, and may contain confidential, privileged or protected information. Any unauthorized use or dissemination of this communication is prohibited. If you received this message in error, please immediately notify the sender and destroy all copies of this message. The recipient should check this email and any attachments for the presence of viruses, as we accept no liability for any damage caused by any virus transmitted by this email.
